### ISSUE TITLE
Initial roadmap

### ISSUE THREAD

**Issue by AridAjd** [lumin-dev/Aegis#1]
Here's the roadmap for Aegis:

- [x] Create docs
- [x] Create animation system **(This excludes TweenService)**
- [x] Create GH actions
- [x] Create state management
- [x] Create instance creation
- [x] Create instance management system
- [x] Add proper logs and debugging functions
- [x] Do proper commenting **(Important for understanding internally)**

**Comment by AridAjd** [comment]
[5a45c00](https://github.com/AridAjd/Robax/commit/5a45c007fa8379340528c1d12c0f9cebc836d7b5) adds the following functions:
```lua
State.Create(initialState: { [any]: any }, ProtectType: boolean?): State
State.Set(self: self, Key: any, newValue: any)
State.Get(self: self, Key: any?)
State.Listen(self: self, Key: any, fn: (oldValue: any, newValue: any) -> ())

State.__joinDictionary(self: self, ...) -- Private
```

And the following types for State:
```lua
type self = {
	__initialState: { [any]: any },
	__state: { [any]: any },
	__listeners: { [any]: () -> () },
	__protectType: boolean,

	__joinDictionary: (self: self, ...any) -> { [any]: any },
	Get: (self: self, Key: any?) -> any,
}

export type State = typeof(setmetatable({} :: self, State))
```

**Comment by AridAjd** [comment]
2fd6b14 finishes the state management system. Here's how it is now:
```lua
Get: <T>(key: string?, defaultValue: T?) -> T,
Set: (self: self, ...{ path: string, value: any }) -> (),
Listen: (self: self, paths: { string }, fn: (pathChanged: string, newValue: any) -> ()) -> (),
```

Types:
```lua
type self = {
	ClassName: "Robax.State",

	__state: { [string]: any },
	__listeners: {},
	__protectType: boolean,

	Get: <T>(key: string?, defaultValue: T?) -> T,
	Set: (self: self, ...{ path: string, value: any }) -> (),
	Listen: (self: self, paths: { string }, fn: (pathChanged: string, newValue: any) -> ()) -> (),
}

export type State = typeof(setmetatable({} :: self, { __index = Class }))
```

Example code:
```lua
local Robax = require(game:GetService("ReplicatedStorage").Robax)
local State = Robax.State

local Value = State({
    Name = "Arid",
    Age = 16,
    Hobbies = {
        Hobby1 = "Programming",
        Hobby2 = "Playing soccer"
    }
})

print(Value:Get())

Value:Set({
    path = "Name",
    value = "James"
})

Value:Listen({"Name", "Hobbies/Hobby2"}, function(keyChanged: string, newValue: any)
    print(keyChanged, newValue)
end)

print(Value:Get())

Value:Set({
    path = "Name",
    value = "NotRealBubba"
}, {
    path = "Age",
    value = "[REDACTED]"
})

print("changed name and age")

Value:Set({
    path = "Hobbies/Hobby2",
    value = "Making games"
})

print("changed hobby 2")
```
![image](https://github.com/AridAjd/Robax/assets/118916772/8c60c9b2-18c6-41ce-a915-b80e9db1e7af)

**Comment by AridAjd** [comment]
There is a whole lot to talk about in 8d973b5!

1. I updated the Build function to be more dynamic and it now properly skips over the Parent property if provided in the props table.
2. Separated the entire utility functions into a separate script for organization.
3. Added various special keys. Here they are:
    - Children
    - Events (to be fixed)
    - Changes (to be fixed)
    - Attributes (to be fixed)
    - Tags (to be fixed)

TODO:
1. Fix children not being parented to top-level instance.
2. Fix tags and attributes not being set to top-level instance.
3. Fix events and changes not being connected to top-level instance.

I'm suspecting the `Key.Apply` function isn't running which skips over it. I'll try fixing it in the next commit!

**Comment by AridAjd** [comment]
[e8ceded](https://github.com/AridAjd/Robax/commit/e8ceded80e67f5fe4d383836f6b127bcc421c82e) fixes the above issues. The problem wasn't with the `Key.Apply` function, rather with a small oversight on every Key module which caused the `Utils.ApplySpecialKeyProperty` to be skipped.

1. Basically, the `ClassName` property wasn't provided which caused it to skip over every special key property.
2. Second, the Children key now also accepts a singular instance rather than an entire table to improve memory.

A benchmark will be given on the current progress soon.

**Comment by AridAjd** [comment]
From now on, constructors will use `camelCase` instead of `PascalCase` for constructors. The constructors so far includes:

```lua
Aegis.new(className: string) -> AegisInstance
Aegis.component() -> AegisComponent -- [WIP]
Aegis.state(initialValue: any) -> AegisState
Aegis.spring(springConfig: springConfig) -> AegisSpring
```

**Comment by AridAjd** [comment]
## A small internal rewrite
- [ ] Fix function call order
- [ ] `APIs` -> `Constructors`
- [ ] Separate `new` constructor and remove its metatable
- [ ] `component` constructor (aka API) -> `Component` key

**Comment by AridAjd** [comment]
## Aegis is now here! :tada:
